services:
  mysql-9:
    image: mysql:9.7.0
    container_name: mysql-local
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_TIME_ZONE: '+08:00'
      MYSQL_DATABASE: boot-db
      MYSQL_USER: boot
      MYSQL_PASSWORD: boot
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-config/my.cnf:/etc/mysql/conf.d/my.cnf:0644

volumes:
  mysql_data:
