[versions]
spring-boot-version = "4.1.1"
spring-dependency-management = "1.1.7"
mybatis-version = "4.1.0"

[plugins]
springBoot = { id = 'org.springframework.boot', version.ref = "spring-boot-version" }
springDependencyManagement = { id = 'io.spring.dependency-management', version.ref = "spring-dependency-management" }

[libraries]
mybatis = {group="org.mybatis.spring.boot", name="mybatis-spring-boot-starter", version.ref='mybatis-version'}